"""Theme palettes and color helpers (no GUI imports)."""

import platform

# Linux X11 bitmap fonts cannot render emoji (U+1F000+) or many extended
# Unicode symbols.  Provide plain-text fallbacks for Linux while keeping
# emoji on macOS / Windows where they render normally.
_IS_LINUX = platform.system() == "Linux"

# ── Theme Definitions (Catppuccin-inspired) ──────────────────────────
THEMES = {
    "dark": {
        "bg":              "#0d1117",
        "bg_secondary":    "#161b22",
        "bg_tertiary":     "#21262d",
        "fg":              "#e6edf3",
        "fg_dim":          "#7d8590",
        "fg_placeholder":  "#484f58",
        "accent":          "#58a6ff",
        "accent_hover":    "#79c0ff",
        "accent_green":    "#3fb950",
        "accent_url":      "#58a6ff",
        "accent_red":      "#f85149",
        "border":          "#30363d",
        "border_light":    "#484f58",
        "button_bg":       "#21262d",
        "button_fg":       "#e6edf3",
        "button_hover":    "#30363d",
        "button_active":   "#484f58",
        "check_bg":        "#21262d",
        "check_fg":        "#e6edf3",
        "check_select":    "#58a6ff",
        "entry_bg":        "#0d1117",
        "entry_fg":        "#e6edf3",
        "entry_border":    "#30363d",
        "combo_bg":        "#0d1117",
        "combo_fg":        "#e6edf3",
        "combo_select_bg": "#30363d",
        "list_bg":         "#0d1117",
        "list_fg":         "#e6edf3",
        "list_select_bg":  "#1f6feb",
        "list_select_fg":  "#ffffff",
        "text_bg":         "#0d1117",
        "text_fg":         "#e6edf3",
        "text_select_bg":  "#1f6feb",
        "text_insert":     "#e6edf3",
        "scrollbar_bg":    "#484f58",
        "scrollbar_trough":"#0d1117",
        "scrollbar_active":"#6e7681",
        "scrollbar_arrow": "#e6edf3",
        "menu_bg":         "#161b22",
        "menu_fg":         "#e6edf3",
        "menu_active_bg":  "#1f6feb",
        "menu_active_fg":  "#ffffff",
        "separator":       "#30363d",
        "paned_sash":      "#30363d",
        "label_frame_fg":  "#7d8590",
        "viewer_toolbar":  "#161b22",
        "viewer_canvas":   "#0d1117",
        "viewer_btn":      "#1f6feb",
        "viewer_btn_hover":"#388bfd",
        "theme_icon":      "☀️" if not _IS_LINUX else "亮",
        "hl_red":          "#cc3333",
        "hl_yellow":       "#b8a020",
        "hl_orange":       "#cc7520",
        "hl_green":        "#33aa44",
        "hl_purple":       "#8839ef",
    },
    "light": {
        "bg":              "#eff1f5",
        "bg_secondary":    "#e6e9ef",
        "bg_tertiary":     "#dce0e8",
        "fg":              "#4c4f69",
        "fg_dim":          "#8c8fa1",
        "fg_placeholder":  "#9ca0b0",
        "accent":          "#1e66f5",
        "accent_hover":    "#2c78f7",
        "accent_green":    "#40a02b",
        "accent_url":      "#1e66f5",
        "accent_red":      "#d20f39",
        "border":          "#ccd0da",
        "border_light":    "#bcc0cc",
        "button_bg":       "#dce0e8",
        "button_fg":       "#4c4f69",
        "button_hover":    "#ccd0da",
        "button_active":   "#bcc0cc",
        "check_bg":        "#dce0e8",
        "check_fg":        "#4c4f69",
        "check_select":    "#1e66f5",
        "entry_bg":        "#ffffff",
        "entry_fg":        "#4c4f69",
        "entry_border":    "#ccd0da",
        "combo_bg":        "#ffffff",
        "combo_fg":        "#4c4f69",
        "combo_select_bg": "#ccd0da",
        "list_bg":         "#eff1f5",
        "list_fg":         "#4c4f69",
        "list_select_bg":  "#ccd0da",
        "list_select_fg":  "#4c4f69",
        "text_bg":         "#ffffff",
        "text_fg":         "#4c4f69",
        "text_select_bg":  "#ccd0da",
        "text_insert":     "#4c4f69",
        "scrollbar_bg":    "#bcc0cc",
        "scrollbar_trough":"#e6e9ef",
        "scrollbar_active":"#9ca0b0",
        "scrollbar_arrow": "#4c4f69",
        "menu_bg":         "#e6e9ef",
        "menu_fg":         "#4c4f69",
        "menu_active_bg":  "#ccd0da",
        "menu_active_fg":  "#4c4f69",
        "separator":       "#ccd0da",
        "paned_sash":      "#ccd0da",
        "label_frame_fg":  "#6c6f85",
        "viewer_toolbar":  "#dce0e8",
        "viewer_canvas":   "#e6e9ef",
        "viewer_btn":      "#1e66f5",
        "viewer_btn_hover":"#2c78f7",
        "theme_icon":      "\U0001f319" if not _IS_LINUX else "暗",
        "hl_red":          "#ff3333",
        "hl_yellow":       "#e6c800",
        "hl_orange":       "#ff8c00",
        "hl_green":        "#22bb44",
        "hl_purple":       "#a855f7",
    },
}

HIGHLIGHT_NAMES = ("green", "yellow", "red", "orange", "purple")


def blend(hex_a, hex_b, ratio):
    """Blend two #rrggbb colors; ratio 0 → hex_a, 1 → hex_b."""
    a = tuple(int(hex_a[i:i + 2], 16) for i in (1, 3, 5))
    b = tuple(int(hex_b[i:i + 2], 16) for i in (1, 3, 5))
    c = tuple(round(a[i] + (b[i] - a[i]) * ratio) for i in range(3))
    return "#%02x%02x%02x" % c
